run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocritic
    - gocyclo
    - misspell
    - revive
    - unconvert
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 15

  revive:
    rules:
      - name: exported
        disabled: false
      - name: indent-error-flow
        disabled: false

  govet:
    enable-all: true
    disable:
      - shadow

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
