version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gocritic
    - gocyclo
    - misspell
    - revive
    - unconvert
    - unparam

settings:
  gocyclo:
    min-complexity: 15

  revive:
    rules:
      - name: exported
        disabled: false
      - name: indent-error-flow
        disabled: false

  govet:
    enable-all: true
    disable:
      - shadow

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
