version: '3'

vars:
  BINARY_NAME: claude-sync
  BUILD_DIR: bin
  MAIN_PACKAGE: .

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install-tools:
    desc: Install development tools
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install gotest.tools/gotestsum@latest

  build:
    desc: Build the binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -v -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PACKAGE}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  install:
    desc: Install the binary to $GOPATH/bin
    cmds:
      - go install {{.MAIN_PACKAGE}}

  test:
    desc: Run tests
    cmds:
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

  test-verbose:
    desc: Run tests with verbose output
    cmds:
      - go test -v -race -count=1 ./...

  test-coverage:
    desc: Run tests and show coverage
    cmds:
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - go tool cover -html=coverage.txt -o coverage.html
      - echo "Coverage report generated: coverage.html"

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...

  lint-fix:
    desc: Run linter and auto-fix issues
    cmds:
      - golangci-lint run --fix ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - gofmt -s -w .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  tidy:
    desc: Tidy go.mod
    cmds:
      - go mod tidy
      - go mod verify

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.txt coverage.html

  check:
    desc: Run all checks (fmt, vet, lint, test)
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test

  ci:
    desc: Run CI checks locally
    cmds:
      - task: tidy
      - task: check

  run:
    desc: Build and run the application
    cmds:
      - task: build
      - ./{{.BUILD_DIR}}/{{.BINARY_NAME}}

  dev:
    desc: Run in development mode (build + run)
    cmds:
      - go run {{.MAIN_PACKAGE}} {{.CLI_ARGS}}
