version: '3'

vars:
  BINARY_NAME: claude-sync
  BUILD_DIR: bin
  MAIN_PACKAGE: .
  GIT_TAG:
    sh: git describe --tags --exact-match 2>/dev/null || echo "dev"
  GIT_COMMIT:
    sh: git rev-parse HEAD 2>/dev/null || echo "unknown"
  BUILD_DATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  LDFLAGS: >-
    -s -w
    -X "github.com/mfenderov/claude-sync/internal/version.Version={{.GIT_TAG}}"
    -X "github.com/mfenderov/claude-sync/internal/version.Commit={{.GIT_COMMIT}}"
    -X "github.com/mfenderov/claude-sync/internal/version.Date={{.BUILD_DATE}}"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install-tools:
    desc: Install development tools
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install gotest.tools/gotestsum@latest
      - go install github.com/vektra/mockery/v3@latest

  build:
    desc: Build the binary with version info
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -v -ldflags "{{.LDFLAGS}}" -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PACKAGE}}
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY_NAME}}"

  install:
    desc: Install the binary to $GOPATH/bin with version info
    cmds:
      - go install -ldflags "{{.LDFLAGS}}" {{.MAIN_PACKAGE}}

  generate-mocks:
    desc: Generate mocks using mockery
    cmds:
      - mockery

  test:
    desc: Run tests
    deps: [generate-mocks]
    cmds:
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

  test-verbose:
    desc: Run tests with verbose output
    deps: [generate-mocks]
    cmds:
      - go test -v -race -count=1 ./...

  test-coverage:
    desc: Run tests and show coverage
    deps: [generate-mocks]
    cmds:
      - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - go tool cover -html=coverage.txt -o coverage.html
      - echo "Coverage report generated in coverage.html"

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...

  lint-fix:
    desc: Run linter and auto-fix issues
    cmds:
      - golangci-lint run --fix ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - gofmt -s -w .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  tidy:
    desc: Tidy go.mod
    cmds:
      - go mod tidy
      - go mod verify

  clean:
    desc: Clean build artifacts and generated mocks
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.txt coverage.html
      - find . -name '*_mock.go' -delete

  check:
    desc: Run all checks (fmt, vet, lint, test)
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test

  ci:
    desc: Run CI checks locally
    cmds:
      - task: tidy
      - task: check

  run:
    desc: Build and run the application
    cmds:
      - task: build
      - ./{{.BUILD_DIR}}/{{.BINARY_NAME}}

  dev:
    desc: Run in development mode (build + run)
    cmds:
      - go run -ldflags "{{.LDFLAGS}}" {{.MAIN_PACKAGE}} {{.CLI_ARGS}}